# Generated by Django 3.1.2 on 2020-12-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='watch',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='watch',
            field=models.ManyToManyField(blank=True, null=True, related_name='watched_listings', to='auctions.Listing'),
        ),
    ]
