# Generated by Django 3.1.2 on 2020-12-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20201212_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='watch',
            field=models.ManyToManyField(to='auctions.Listing'),
        ),
    ]
