# Generated by Django 3.1.2 on 2020-12-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20201217_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='active',
            field=models.BooleanField(default=True, null=True, verbose_name='Is active'),
        ),
    ]
