# Generated by Django 3.1.2 on 2020-12-23 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='user',
        ),
    ]
