# Generated by Django 3.1.2 on 2020-12-25 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_remove_listing_latestbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='latestbid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lastest_bid', to='auctions.bid'),
        ),
    ]
