# Generated by Django 3.1.2 on 2020-12-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20201228_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='allbids',
            field=models.ManyToManyField(blank=True, related_name='all_bids_for_auction', to='auctions.Bid'),
        ),
    ]
