# Generated by Django 3.1.2 on 2021-01-01 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_listing_allbids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alllisting',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
